name: tiktok_tutorial
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cached_network_image: ^3.3.1
  cloud_firestore: ^6.1.0
  cupertino_icons: ^1.0.8
  firebase_auth: ^6.1.2
  firebase_core: ^4.2.1
  firebase_storage: ^13.0.4
  get: ^4.6.6
  image_picker: ^1.1.2
  timeago: ^3.6.1
  video_compress: ^3.1.0
  video_player: ^2.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
